"""
FAISS-based retrieval module for KNN classification and few-shot context generation.

Responsibilities:
  - Loading the FAISS index and metadata
  - Searching for k nearest neighbours given a query embedding
  - Cosine-weighted KNN majority vote classification
  - Formatting neighbours into few-shot prompt context

Expects (generated by data pipeline):
  - data/processed/corpus.index: FAISS IndexFlatIP with 768-dim L2-normalized train vectors
  - data/processed/corpus.jsonl: Full corpus with labels and metadata
  - data/processed/train_indices.npy: Indices of train samples

Backend Integration:
    from src.inference import FAISSRetriever

    # Load once at app startup
    retriever = FAISSRetriever()

    # On each request
    result = retriever.retrieve_and_classify(query_embedding)

    # Access results:
    # result.knn_label - "ai" or "human"
    # result.knn_confidence - 0.0 to 1.0
    # result.neighbours - list of Neighbour objects for evidence
    # result.few_shot_prompt - formatted context for LLM
"""

import json
import os
import numpy as np
import faiss
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

EMBEDDING_DIM = 768
K_NEIGHBOURS = 10

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data", "processed")

INDEX_PATH = Path(os.path.join(PROCESSED_DIR, "corpus.index"))
CORPUS_PATH = Path(os.path.join(PROCESSED_DIR, "corpus.jsonl"))
TRAIN_INDICES_PATH = Path(os.path.join(PROCESSED_DIR, "train_indices.npy"))


@dataclass
class Neighbour:
    """One retrieved neighbour from the FAISS index."""
    rank: int
    text: str
    label: str
    source_model: Optional[str]
    platform: str
    cosine_similarity: float


@dataclass
class RetrievalResult:
    """Complete retrieval result with KNN verdict, evidence, and LLM context."""
    knn_label: str
    knn_confidence: float
    neighbours: list[Neighbour]
    few_shot_prompt: str
    label_counts: dict = field(default_factory=dict)


class FAISSRetriever:
    """Loads FAISS index and provides KNN search and classification.

    Thread-safe for read-only searches. Load once at app startup.
    """

    def __init__(
        self,
        index_path: Path = INDEX_PATH,
        corpus_path: Path = CORPUS_PATH,
        train_indices_path: Path = TRAIN_INDICES_PATH,
        k: int = K_NEIGHBOURS,
        embedding_dim: int = EMBEDDING_DIM,
    ):
        self.k = k
        self.embedding_dim = embedding_dim

        if not index_path.exists():
            raise FileNotFoundError(
                f"FAISS index not found at {index_path}. "
                "Run build_index.py first."
            )
        self.index = faiss.read_index(str(index_path))

        if self.index.d != embedding_dim:
            raise ValueError(
                f"Index has {self.index.d} dims but EMBEDDING_DIM={embedding_dim}."
            )

        if not train_indices_path.exists():
            raise FileNotFoundError(
                f"Train indices file not found at {train_indices_path}. "
                "Run build_index.py first."
            )
        train_indices = np.load(train_indices_path)

        if not corpus_path.exists():
            raise FileNotFoundError(
                f"Corpus file not found at {corpus_path}. "
                "Run preprocess.py first."
            )
        self.metadata: list[dict] = []
        with open(corpus_path, "r", encoding="utf-8") as f:
            corpus = [json.loads(line.strip()) for line in f if line.strip()]

        for idx in train_indices:
            if idx < len(corpus):
                self.metadata.append(corpus[idx])
            else:
                raise ValueError(
                    f"Train index {idx} out of bounds for corpus (size={len(corpus)})"
                )

        if len(self.metadata) != self.index.ntotal:
            raise ValueError(
                f"Metadata has {len(self.metadata)} entries but "
                f"FAISS index has {self.index.ntotal} vectors."
            )

        print(f"FAISSRetriever loaded: {self.index.ntotal:,} train vectors at {embedding_dim} dims | k={k}")

    def search(self, query_embedding: np.ndarray) -> list[Neighbour]:
        """Search FAISS for k nearest neighbours by cosine similarity.

        Args:
            query_embedding: 768-dim float32 array from Gemini Embedding API

        Returns:
            List of Neighbour objects sorted by cosine similarity descending
        """
        query_embedding = np.array(query_embedding, dtype=np.float32)
        if query_embedding.ndim == 1:
            query_embedding = query_embedding.reshape(1, -1)

        if query_embedding.shape[1] != self.embedding_dim:
            raise ValueError(
                f"Query embedding has {query_embedding.shape[1]} dims, expected {self.embedding_dim}."
            )

        faiss.normalize_L2(query_embedding)
        similarities, indices = self.index.search(query_embedding, self.k)

        similarities = similarities[0]
        indices = indices[0]

        neighbours = []
        for rank, (idx, sim) in enumerate(zip(indices, similarities), start=1):
            if idx == -1:
                continue
            meta = self.metadata[idx]
            neighbours.append(Neighbour(
                rank=rank,
                text=meta["text"],
                label=meta["label"],
                source_model=meta.get("source_model"),
                platform=meta.get("platform", "unknown"),
                cosine_similarity=float(sim),
            ))

        return neighbours

    def knn_classify(self, neighbours: list[Neighbour]) -> tuple[str, float, dict]:
        """Cosine-weighted majority vote classification.

        Args:
            neighbours: List of Neighbour objects from search()

        Returns:
            (predicted_label, confidence, label_counts)
        """
        weighted_votes: dict[str, float] = {"ai": 0.0, "human": 0.0}
        label_counts: dict[str, int] = {"ai": 0, "human": 0}

        for n in neighbours:
            weight = max(0.0, n.cosine_similarity)
            weighted_votes[n.label] += weight
            label_counts[n.label] += 1

        total_weight = sum(weighted_votes.values())

        if total_weight == 0:
            predicted = max(label_counts, key=label_counts.get)
            confidence = label_counts[predicted] / len(neighbours)
        else:
            predicted = max(weighted_votes, key=weighted_votes.get)
            confidence = weighted_votes[predicted] / total_weight

        return predicted, round(confidence, 4), label_counts

    def format_few_shot_prompt(self, neighbours: list[Neighbour]) -> str:
        """Format neighbours into few-shot context for the LLM.

        Warning: The model was fine-tuned on this exact format.
        Do not change without retraining.
        """
        lines = ["## Retrieved examples from reference corpus\n"]

        for n in neighbours:
            source = n.source_model if n.source_model else "human-written"
            lines.append(
                f"[Example {n.rank}] "
                f"Label: {n.label.upper()} | "
                f"Source: {source} | "
                f"Platform: {n.platform} | "
                f"Similarity: {n.cosine_similarity:.3f}\n"
                f"Text: {n.text.strip()}\n"
            )

        return "\n".join(lines)

    def retrieve_and_classify(self, query_embedding: np.ndarray) -> RetrievalResult:
        """Main entry point: search, classify, and format prompt context.

        Args:
            query_embedding: 768-dim float32 numpy array

        Returns:
            RetrievalResult with KNN verdict, confidence, neighbours, and few-shot prompt
        """
        neighbours = self.search(query_embedding)
        knn_label, knn_confidence, label_counts = self.knn_classify(neighbours)
        few_shot_prompt = self.format_few_shot_prompt(neighbours)

        return RetrievalResult(
            knn_label=knn_label,
            knn_confidence=knn_confidence,
            neighbours=neighbours,
            few_shot_prompt=few_shot_prompt,
            label_counts=label_counts,
        )


# Quick smoke test
if __name__ == "__main__":
    print("Running smoke test with random vector...")
    retriever = FAISSRetriever()
    dummy_embedding = np.random.randn(EMBEDDING_DIM).astype(np.float32)
    result = retriever.retrieve_and_classify(dummy_embedding)

    print(f"\nKNN verdict : {result.knn_label.upper()}")
    print(f"Confidence  : {result.knn_confidence:.1%}")
    print(f"Vote counts : {result.label_counts}")
    print(f"\nTop 3 neighbours:")
    for n in result.neighbours[:3]:
        print(f"  [{n.rank}] {n.label.upper()} | sim={n.cosine_similarity:.3f} | {n.platform} | {n.text[:80]}...")
    print(f"\nFew-shot prompt (first 300 chars):")
    print(result.few_shot_prompt[:300])
