#!/usr/bin/env python3
"""Local MPS inference for the merged Llama checkpoint."""

from __future__ import annotations

import argparse
from pathlib import Path

import torch


SYSTEM_PROMPT = (
    "You are a classifier that determines whether a social media post was "
    "written by a human or generated by AI. Respond with exactly one word: "
    "'ai' or 'human'."
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run local inference with a merged model on MPS.")
    parser.add_argument(
        "--model_path",
        default="model_merged",
        help="Path to the merged local model directory.",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--text", help="Raw post text to classify.")
    group.add_argument(
        "--instruction",
        help="Full instruction prompt. Use this if you want to pass a prebuilt RAG prompt.",
    )
    parser.add_argument("--max_seq_length", type=int, default=2048)
    parser.add_argument(
        "--device",
        choices=["auto", "mps", "cpu"],
        default="auto",
        help="Inference device. auto prefers MPS, then CPU.",
    )
    return parser.parse_args()


def build_prompt(raw_input: str, tokenizer, is_instruction: bool) -> str:
    if is_instruction:
        user_content = raw_input
    else:
        user_content = (
            "Classify the following social media post as either 'ai' or 'human'.\n\n"
            f"Post: {raw_input}"
        )

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]
    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )


def get_label_tokens(tokenizer) -> tuple[int, int]:
    ai_ids = tokenizer("ai", add_special_tokens=False).input_ids
    human_ids = tokenizer("human", add_special_tokens=False).input_ids
    if len(ai_ids) != 1 or len(human_ids) != 1:
        raise ValueError(
            "Merged tokenizer does not tokenize 'ai'/'human' as single tokens. "
            "This local inference path assumes the same label-token setup as training."
        )
    return ai_ids[0], human_ids[0]


def main() -> None:
    args = parse_args()
    model_path = Path(args.model_path).expanduser().resolve()
    if not model_path.exists():
        raise FileNotFoundError(
            f"Merged model not found at {model_path}. Run scripts/merge_lora.py first."
        )

    try:
        from transformers import AutoModelForCausalLM, AutoTokenizer
    except ImportError as exc:
        raise RuntimeError(
            "Missing local inference dependencies. Install with:\n"
            "uv pip install torch transformers accelerate safetensors sentencepiece"
        ) from exc

    if args.device == "auto":
        device = "mps" if torch.backends.mps.is_available() else "cpu"
    else:
        device = args.device
    print(f"Loading merged model from: {model_path}")
    print(f"Device: {device}")

    tokenizer = AutoTokenizer.from_pretrained(str(model_path), use_fast=True)
    model_kwargs = {"low_cpu_mem_usage": True}
    if device == "mps":
        model_kwargs["dtype"] = torch.float16
    model = AutoModelForCausalLM.from_pretrained(str(model_path), **model_kwargs)
    model.to(device)
    model.eval()

    ai_token_id, human_token_id = get_label_tokens(tokenizer)
    prompt = build_prompt(
        args.instruction if args.instruction is not None else args.text,
        tokenizer,
        is_instruction=args.instruction is not None,
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=args.max_seq_length,
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=1,
            output_scores=True,
            return_dict_in_generate=True,
            do_sample=False,
            use_cache=True,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    logits = outputs.scores[0][0]
    probs = torch.softmax(logits, dim=-1)
    ai_probability = probs[ai_token_id].item()
    human_probability = probs[human_token_id].item()
    generated_id = outputs.sequences[0][-1].item()
    generated_token = tokenizer.decode([generated_id])

    prediction = "ai" if generated_id == ai_token_id else "human" if generated_id == human_token_id else "unknown"

    print(f"Prediction: {prediction}")
    print(f"First token: {generated_token!r} (id={generated_id})")
    print(f"P(ai): {ai_probability:.6f}")
    print(f"P(human): {human_probability:.6f}")


if __name__ == "__main__":
    main()
