"""Step 5: Generate training data with and without RAG context."""

import json
import os

import faiss
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data", "processed")
CORPUS_PATH = os.path.join(PROCESSED_DIR, "corpus.jsonl")
EMBEDDINGS_PATH = os.path.join(PROCESSED_DIR, "embeddings.npy")
INDEX_PATH = os.path.join(PROCESSED_DIR, "corpus.index")
TRAIN_INDICES_PATH = os.path.join(PROCESSED_DIR, "train_indices.npy")
SPLITS_PATH = os.path.join(PROCESSED_DIR, "splits.json")

K_NEIGHBORS = 10
K_SEARCH = K_NEIGHBORS + 1  # extra slot for self-exclusion
K_RAG_CONTEXT = 5
MAX_NEIGHBOR_CHARS = 300
PROGRESS_INTERVAL = 10_000


def build_rag_instruction(target_text, neighbors):
    """Build instruction prompt with RAG context from similar texts."""
    context_parts = []
    for i, (text, label) in enumerate(neighbors[:K_RAG_CONTEXT], 1):
        truncated = text[:MAX_NEIGHBOR_CHARS]
        if len(text) > MAX_NEIGHBOR_CHARS:
            truncated += "..."
        context_parts.append(f"Example {i} (label: {label}):\n{truncated}")

    context_block = "\n\n".join(context_parts)

    instruction = (
        "You are a classifier that determines whether a social media post was written by "
        "a human or generated by AI.\n\n"
        "Here are some similar texts and their labels for reference:\n\n"
        f"{context_block}\n\n"
        "Now classify the following post as either 'ai' or 'human'.\n\n"
        f"Post: {target_text}"
    )
    return instruction


def build_plain_instruction(target_text):
    """Build instruction prompt without RAG context."""
    instruction = (
        "You are a classifier that determines whether a social media post was written by "
        "a human or generated by AI.\n\n"
        "Classify the following post as either 'ai' or 'human'.\n\n"
        f"Post: {target_text}"
    )
    return instruction


def generate_split_data(split_name, record_indices, corpus, embeddings,
                        search_index, local_to_corpus):
    """Generate RAG and plain training data for a single split.

    search_index: FAISS index to search for neighbors (train-only)
    local_to_corpus: list mapping search_index positions back to corpus indices
    """
    rag_path = os.path.join(PROCESSED_DIR, f"{split_name}_with_rag.jsonl")
    plain_path = os.path.join(PROCESSED_DIR, f"{split_name}_without_rag.jsonl")
    count = len(record_indices)

    print(f"\n  Generating {split_name} split ({count} records)...")
    with (
        open(rag_path, "w", encoding="utf-8") as f_rag,
        open(plain_path, "w", encoding="utf-8") as f_plain,
    ):
        for progress, i in enumerate(record_indices):
            record = corpus[i]
            target_text = record["text"]
            target_label = record["label"]

            # Search for neighbors in the train-only index
            query = embeddings[i : i + 1].copy()
            faiss.normalize_L2(query)
            scores, indices = search_index.search(query, K_SEARCH)

            # Collect neighbors excluding self (map back to corpus indices)
            neighbors = []
            for local_idx in indices[0]:
                if local_idx < 0 or local_idx >= len(local_to_corpus):
                    continue
                corpus_idx = local_to_corpus[local_idx]
                # For train queries, skip self. For val/test, self is never in the train index.
                if corpus_idx == i:
                    continue
                neighbor = corpus[corpus_idx]
                neighbors.append((neighbor["text"], neighbor["label"]))
                if len(neighbors) >= K_NEIGHBORS:
                    break

            # With RAG
            rag_instruction = build_rag_instruction(target_text, neighbors)
            f_rag.write(json.dumps({
                "instruction": rag_instruction,
                "output": target_label,
            }, ensure_ascii=False) + "\n")

            # Without RAG
            plain_instruction = build_plain_instruction(target_text)
            f_plain.write(json.dumps({
                "instruction": plain_instruction,
                "output": target_label,
            }, ensure_ascii=False) + "\n")

            if (progress + 1) % PROGRESS_INTERVAL == 0 or progress == count - 1:
                print(f"    [{progress+1}/{count}] {100*(progress+1)/count:.1f}%")

    rag_size = os.path.getsize(rag_path) / (1024 * 1024)
    plain_size = os.path.getsize(plain_path) / (1024 * 1024)
    print(f"    {rag_path} ({rag_size:.1f} MB, {count} records)")
    print(f"    {plain_path} ({plain_size:.1f} MB, {count} records)")


def main():
    # Load corpus
    print("Loading corpus...")
    corpus = []
    with open(CORPUS_PATH, "r", encoding="utf-8") as f:
        for line in f:
            corpus.append(json.loads(line))
    total = len(corpus)
    print(f"  Corpus size: {total}")

    # Load splits
    print("Loading splits...")
    with open(SPLITS_PATH, "r", encoding="utf-8") as f:
        splits = json.load(f)
    print(f"  Split assignments: {len(splits)}")

    # Group corpus indices by split
    split_indices = {"train": [], "val": [], "test": []}
    for i, record in enumerate(corpus):
        split_name = splits.get(str(record["id"]))
        if split_name in split_indices:
            split_indices[split_name].append(i)
    for name, indices in split_indices.items():
        print(f"  {name}: {len(indices)} records")

    # Load embeddings
    print("Loading embeddings...")
    embeddings = np.load(EMBEDDINGS_PATH)
    print(f"  Embeddings shape: {embeddings.shape}")

    assert total == embeddings.shape[0], (
        f"Size mismatch: corpus={total}, embeddings={embeddings.shape[0]}"
    )

    # Load pre-built train-only FAISS index (from build_index.py)
    # All splits retrieve neighbors exclusively from the training set,
    # so val/test evaluation is not inflated by held-out examples.
    print(f"\nLoading train-only FAISS index from {INDEX_PATH}...")
    train_index = faiss.read_index(INDEX_PATH)
    print(f"  Train index size: {train_index.ntotal}")

    # Load or derive the local-to-corpus index mapping
    local_to_corpus = list(np.load(TRAIN_INDICES_PATH))
    assert train_index.ntotal == len(local_to_corpus), (
        f"Index/mapping mismatch: index has {train_index.ntotal} vectors "
        f"but mapping has {len(local_to_corpus)} entries"
    )

    # Generate data for each split (all search against train-only index)
    print(f"\nGenerating split data...")
    for split_name in ("train", "val", "test"):
        generate_split_data(
            split_name, split_indices[split_name],
            corpus, embeddings, train_index, local_to_corpus,
        )

    print(f"\nDone!")


if __name__ == "__main__":
    main()
