"""Build balanced training data: undersample AI, rebuild FAISS, regenerate JSONL.

Addresses the 4.18:1 AI/human imbalance in the training split by:
1. Undersampling AI train examples to match the human count (~67K each → ~134K total)
2. Rebuilding the FAISS index on the balanced subset only
3. Regenerating all 6 JSONL files (train/val/test × with/without RAG) using the balanced index

No Gemini API calls needed — reuses existing embeddings.npy.
Original pipeline outputs are preserved; new files use '_balanced' suffix.
"""

import json
import os
import random

import faiss
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
CORE_DIR = os.path.join(PROJECT_ROOT, "data", "processed", "core")
TRAINING_DIR = os.path.join(PROJECT_ROOT, "data", "processed", "training")

# Input paths (from original pipeline)
CORPUS_PATH = os.path.join(CORE_DIR, "corpus.jsonl")
SPLITS_PATH = os.path.join(CORE_DIR, "splits.json")
EMBEDDINGS_PATH = os.path.join(CORE_DIR, "embeddings.npy")

# Output paths (balanced)
BALANCED_TRAIN_INDICES_PATH = os.path.join(CORE_DIR, "balanced_train_indices.npy")
BALANCED_INDEX_PATH = os.path.join(CORE_DIR, "corpus_balanced.index")
BALANCED_MAPPING_PATH = os.path.join(CORE_DIR, "train_indices_balanced.npy")

DIMENSIONS = 768
SEED = 42

# RAG constants (same as build_training_data.py)
K_NEIGHBORS = 10
K_SEARCH = K_NEIGHBORS + 1
K_RAG_CONTEXT = 5
MAX_NEIGHBOR_CHARS = 300
PROGRESS_INTERVAL = 10_000


def build_rag_instruction(target_text, neighbors):
    context_parts = []
    for i, (text, label) in enumerate(neighbors[:K_RAG_CONTEXT], 1):
        truncated = text[:MAX_NEIGHBOR_CHARS]
        if len(text) > MAX_NEIGHBOR_CHARS:
            truncated += "..."
        context_parts.append(f"Example {i} (label: {label}):\n{truncated}")

    context_block = "\n\n".join(context_parts)

    instruction = (
        "You are a classifier that determines whether a social media post was written by "
        "a human or generated by AI.\n\n"
        "Here are some similar texts and their labels for reference:\n\n"
        f"{context_block}\n\n"
        "Now classify the following post as either 'ai' or 'human'.\n\n"
        f"Post: {target_text}"
    )
    return instruction


def build_plain_instruction(target_text):
    instruction = (
        "You are a classifier that determines whether a social media post was written by "
        "a human or generated by AI.\n\n"
        "Classify the following post as either 'ai' or 'human'.\n\n"
        f"Post: {target_text}"
    )
    return instruction


def generate_split_data(split_name, record_indices, corpus, embeddings,
                        search_index, local_to_corpus, output_prefix):
    rag_path = os.path.join(TRAINING_DIR, f"{output_prefix}_balanced_with_rag.jsonl")
    plain_path = os.path.join(TRAINING_DIR, f"{output_prefix}_balanced_without_rag.jsonl")
    count = len(record_indices)

    print(f"\n  Generating {split_name} split ({count} records)...")
    with (
        open(rag_path, "w", encoding="utf-8") as f_rag,
        open(plain_path, "w", encoding="utf-8") as f_plain,
    ):
        for progress, i in enumerate(record_indices):
            record = corpus[i]
            target_text = record["text"]
            target_label = record["label"]

            query = embeddings[i : i + 1].copy()
            faiss.normalize_L2(query)
            scores, indices = search_index.search(query, K_SEARCH)

            neighbors = []
            for local_idx in indices[0]:
                if local_idx < 0 or local_idx >= len(local_to_corpus):
                    continue
                corpus_idx = local_to_corpus[local_idx]
                if corpus_idx == i:
                    continue
                neighbor = corpus[corpus_idx]
                neighbors.append((neighbor["text"], neighbor["label"]))
                if len(neighbors) >= K_NEIGHBORS:
                    break

            rag_instruction = build_rag_instruction(target_text, neighbors)
            f_rag.write(json.dumps({
                "instruction": rag_instruction,
                "output": target_label,
            }, ensure_ascii=False) + "\n")

            plain_instruction = build_plain_instruction(target_text)
            f_plain.write(json.dumps({
                "instruction": plain_instruction,
                "output": target_label,
            }, ensure_ascii=False) + "\n")

            if (progress + 1) % PROGRESS_INTERVAL == 0 or progress == count - 1:
                print(f"    [{progress+1}/{count}] {100*(progress+1)/count:.1f}%")

    rag_size = os.path.getsize(rag_path) / (1024 * 1024)
    plain_size = os.path.getsize(plain_path) / (1024 * 1024)
    print(f"    {rag_path} ({rag_size:.1f} MB, {count} records)")
    print(f"    {plain_path} ({plain_size:.1f} MB, {count} records)")


def main():
    # ================================================================
    # Step 1: Undersample AI to match human count in train split
    # ================================================================
    print("=" * 60)
    print("Step 1: Undersample AI training examples")
    print("=" * 60)

    print("Loading corpus and splits...")
    corpus = []
    with open(CORPUS_PATH, "r", encoding="utf-8") as f:
        for line in f:
            corpus.append(json.loads(line))
    with open(SPLITS_PATH, "r", encoding="utf-8") as f:
        splits = json.load(f)

    train_by_label = {"ai": [], "human": []}
    for i, record in enumerate(corpus):
        if splits.get(str(record["id"])) == "train":
            train_by_label[record["label"]].append(i)

    n_ai = len(train_by_label["ai"])
    n_human = len(train_by_label["human"])
    print(f"  Train AI: {n_ai}")
    print(f"  Train Human: {n_human}")
    print(f"  Ratio: {n_ai / n_human:.2f}:1")

    random.seed(SEED)
    sampled_ai = random.sample(train_by_label["ai"], n_human)
    balanced_indices = sorted(train_by_label["human"] + sampled_ai)
    print(f"\n  After undersampling:")
    print(f"  AI: {n_human}, Human: {n_human}, Total: {len(balanced_indices)}")

    np.save(BALANCED_TRAIN_INDICES_PATH, np.array(balanced_indices, dtype=np.int64))
    print(f"  Saved: {BALANCED_TRAIN_INDICES_PATH}")

    # ================================================================
    # Step 2: Rebuild FAISS index on balanced subset
    # ================================================================
    print("\n" + "=" * 60)
    print("Step 2: Rebuild FAISS index on balanced training subset")
    print("=" * 60)

    print("Loading embeddings...")
    embeddings = np.load(EMBEDDINGS_PATH)
    print(f"  Shape: {embeddings.shape}, Dtype: {embeddings.dtype}")

    balanced_embeddings = embeddings[balanced_indices].copy()
    print(f"  Balanced embeddings: {balanced_embeddings.shape}")

    print("L2-normalizing...")
    faiss.normalize_L2(balanced_embeddings)

    print(f"Building IndexFlatIP (dim={DIMENSIONS})...")
    index = faiss.IndexFlatIP(DIMENSIONS)
    index.add(balanced_embeddings)
    print(f"  Index size: {index.ntotal} vectors")

    faiss.write_index(index, BALANCED_INDEX_PATH)
    np.save(BALANCED_MAPPING_PATH, np.array(balanced_indices, dtype=np.int64))
    size_mb = os.path.getsize(BALANCED_INDEX_PATH) / (1024 * 1024)
    print(f"  Saved: {BALANCED_INDEX_PATH} ({size_mb:.1f} MB)")
    print(f"  Saved: {BALANCED_MAPPING_PATH} ({len(balanced_indices)} indices)")

    # Sanity check
    print("\n--- Sanity Check ---")
    query = balanced_embeddings[0:1].copy()
    scores, indices_result = index.search(query, 5)
    print("Top 5 neighbors of balanced vector 0:")
    for rank, (idx, score) in enumerate(zip(indices_result[0], scores[0])):
        corpus_idx = balanced_indices[idx] if idx >= 0 else -1
        label = corpus[corpus_idx]["label"] if corpus_idx >= 0 else "?"
        print(f"  #{rank+1}: faiss_idx={idx}, corpus_idx={corpus_idx}, label={label}, sim={score:.6f}")
    if indices_result[0][0] == 0 and scores[0][0] > 0.99:
        print("  OK: self-match with similarity ~1.0")
    else:
        print("  WARNING: first result is not itself")

    # ================================================================
    # Step 3: Regenerate JSONL with balanced FAISS index
    # ================================================================
    print("\n" + "=" * 60)
    print("Step 3: Regenerate training JSONL files")
    print("=" * 60)

    # Group original val/test indices
    split_indices = {"val": [], "test": []}
    for i, record in enumerate(corpus):
        split_name = splits.get(str(record["id"]))
        if split_name in split_indices:
            split_indices[split_name].append(i)

    local_to_corpus = list(np.load(BALANCED_MAPPING_PATH))

    print(f"\nGenerating split data using balanced index ({index.ntotal} vectors)...")

    # Train: use balanced indices only
    generate_split_data("train", balanced_indices, corpus, embeddings,
                        index, local_to_corpus, "train")

    # Val/test: same records, but RAG neighbors from balanced index
    for split_name in ("val", "test"):
        generate_split_data(split_name, split_indices[split_name], corpus, embeddings,
                            index, local_to_corpus, split_name)

    # ================================================================
    # Summary
    # ================================================================
    print("\n" + "=" * 60)
    print("Done! Summary:")
    print("=" * 60)
    for prefix in ("train", "val", "test"):
        for variant in ("with_rag", "without_rag"):
            path = os.path.join(TRAINING_DIR, f"{prefix}_balanced_{variant}.jsonl")
            n_lines = sum(1 for _ in open(path))
            size_mb = os.path.getsize(path) / (1024 * 1024)
            print(f"  {os.path.basename(path)}: {n_lines} records ({size_mb:.1f} MB)")

    # Verify label balance in train files
    print("\nLabel distribution in train_balanced_with_rag.jsonl:")
    counts = {"ai": 0, "human": 0}
    with open(os.path.join(TRAINING_DIR, "train_balanced_with_rag.jsonl")) as f:
        for line in f:
            counts[json.loads(line)["output"]] += 1
    for label, count in counts.items():
        print(f"  {label}: {count} ({100*count/sum(counts.values()):.1f}%)")


if __name__ == "__main__":
    main()
