"""Step 5: Generate training data with and without RAG context."""

import os
import json

import numpy as np
import faiss

PROCESSED_DIR = os.path.join("data", "processed")
CORPUS_PATH = os.path.join(PROCESSED_DIR, "corpus.jsonl")
EMBEDDINGS_PATH = os.path.join(PROCESSED_DIR, "embeddings.npy")
INDEX_PATH = os.path.join(PROCESSED_DIR, "corpus.index")
OUTPUT_WITH_RAG = os.path.join(PROCESSED_DIR, "train_with_rag.jsonl")
OUTPUT_WITHOUT_RAG = os.path.join(PROCESSED_DIR, "train_without_rag.jsonl")

K_SEARCH = 11  # 10 neighbors + self
K_RAG_CONTEXT = 5
MAX_NEIGHBOR_CHARS = 300
PROGRESS_INTERVAL = 10_000


def build_rag_instruction(target_text, neighbors):
    """Build instruction prompt with RAG context from similar texts."""
    context_parts = []
    for i, (text, label) in enumerate(neighbors[:K_RAG_CONTEXT], 1):
        truncated = text[:MAX_NEIGHBOR_CHARS]
        if len(text) > MAX_NEIGHBOR_CHARS:
            truncated += "..."
        context_parts.append(f"Example {i} (label: {label}):\n{truncated}")

    context_block = "\n\n".join(context_parts)

    instruction = (
        "You are a classifier that determines whether a social media post was written by "
        "a human or generated by AI.\n\n"
        "Here are some similar texts and their labels for reference:\n\n"
        f"{context_block}\n\n"
        "Now classify the following post as either 'ai' or 'human'.\n\n"
        f"Post: {target_text}"
    )
    return instruction


def build_plain_instruction(target_text):
    """Build instruction prompt without RAG context."""
    instruction = (
        "You are a classifier that determines whether a social media post was written by "
        "a human or generated by AI.\n\n"
        "Classify the following post as either 'ai' or 'human'.\n\n"
        f"Post: {target_text}"
    )
    return instruction


def main():
    # Load corpus
    print("Loading corpus...")
    corpus = []
    with open(CORPUS_PATH, "r", encoding="utf-8") as f:
        for line in f:
            corpus.append(json.loads(line))
    total = len(corpus)
    print(f"  Corpus size: {total}")

    # Load embeddings and index
    print("Loading embeddings and FAISS index...")
    embeddings = np.load(EMBEDDINGS_PATH)
    faiss.normalize_L2(embeddings)
    index = faiss.read_index(INDEX_PATH)
    print(f"  Embeddings shape: {embeddings.shape}")
    print(f"  Index size: {index.ntotal}")

    assert total == embeddings.shape[0] == index.ntotal, (
        f"Size mismatch: corpus={total}, embeddings={embeddings.shape[0]}, index={index.ntotal}"
    )

    # Generate training data
    print(f"\nGenerating training data...")
    with (
        open(OUTPUT_WITH_RAG, "w", encoding="utf-8") as f_rag,
        open(OUTPUT_WITHOUT_RAG, "w", encoding="utf-8") as f_plain,
    ):
        for i in range(total):
            record = corpus[i]
            target_text = record["text"]
            target_label = record["label"]

            # Search for neighbors
            query = embeddings[i : i + 1].copy()
            scores, indices = index.search(query, K_SEARCH)

            # Collect neighbors excluding self
            neighbors = []
            for idx in indices[0]:
                if idx != i and idx < total:
                    neighbor = corpus[idx]
                    neighbors.append((neighbor["text"], neighbor["label"]))
                if len(neighbors) >= K_SEARCH - 1:
                    break

            # With RAG
            rag_instruction = build_rag_instruction(target_text, neighbors)
            f_rag.write(json.dumps({
                "instruction": rag_instruction,
                "output": target_label,
            }, ensure_ascii=False) + "\n")

            # Without RAG
            plain_instruction = build_plain_instruction(target_text)
            f_plain.write(json.dumps({
                "instruction": plain_instruction,
                "output": target_label,
            }, ensure_ascii=False) + "\n")

            if (i + 1) % PROGRESS_INTERVAL == 0 or i == total - 1:
                print(f"  [{i+1}/{total}] {100*(i+1)/total:.1f}%")

    rag_size = os.path.getsize(OUTPUT_WITH_RAG) / (1024 * 1024)
    plain_size = os.path.getsize(OUTPUT_WITHOUT_RAG) / (1024 * 1024)
    print(f"\nDone!")
    print(f"  {OUTPUT_WITH_RAG} ({rag_size:.1f} MB, {total} records)")
    print(f"  {OUTPUT_WITHOUT_RAG} ({plain_size:.1f} MB, {total} records)")


if __name__ == "__main__":
    main()
