"""Step 5: Generate training data with and without RAG context."""

import json
import os

import faiss
import numpy as np

PROCESSED_DIR = os.path.join("data", "processed")
CORPUS_PATH = os.path.join(PROCESSED_DIR, "corpus.jsonl")
EMBEDDINGS_PATH = os.path.join(PROCESSED_DIR, "embeddings.npy")
INDEX_PATH = os.path.join(PROCESSED_DIR, "corpus.index")
SPLITS_PATH = os.path.join(PROCESSED_DIR, "splits.json")

K_SEARCH = 11  # 10 neighbors + self
K_RAG_CONTEXT = 5
MAX_NEIGHBOR_CHARS = 300
PROGRESS_INTERVAL = 10_000


def build_rag_instruction(target_text, neighbors):
    """Build instruction prompt with RAG context from similar texts."""
    context_parts = []
    for i, (text, label) in enumerate(neighbors[:K_RAG_CONTEXT], 1):
        truncated = text[:MAX_NEIGHBOR_CHARS]
        if len(text) > MAX_NEIGHBOR_CHARS:
            truncated += "..."
        context_parts.append(f"Example {i} (label: {label}):\n{truncated}")

    context_block = "\n\n".join(context_parts)

    instruction = (
        "You are a classifier that determines whether a social media post was written by "
        "a human or generated by AI.\n\n"
        "Here are some similar texts and their labels for reference:\n\n"
        f"{context_block}\n\n"
        "Now classify the following post as either 'ai' or 'human'.\n\n"
        f"Post: {target_text}"
    )
    return instruction


def build_plain_instruction(target_text):
    """Build instruction prompt without RAG context."""
    instruction = (
        "You are a classifier that determines whether a social media post was written by "
        "a human or generated by AI.\n\n"
        "Classify the following post as either 'ai' or 'human'.\n\n"
        f"Post: {target_text}"
    )
    return instruction


def generate_split_data(split_name, record_indices, corpus, embeddings, index, total):
    """Generate RAG and plain training data for a single split."""
    rag_path = os.path.join(PROCESSED_DIR, f"{split_name}_with_rag.jsonl")
    plain_path = os.path.join(PROCESSED_DIR, f"{split_name}_without_rag.jsonl")
    count = len(record_indices)

    print(f"\n  Generating {split_name} split ({count} records)...")
    with (
        open(rag_path, "w", encoding="utf-8") as f_rag,
        open(plain_path, "w", encoding="utf-8") as f_plain,
    ):
        for progress, i in enumerate(record_indices):
            record = corpus[i]
            target_text = record["text"]
            target_label = record["label"]

            # Search for neighbors
            query = embeddings[i : i + 1].copy()
            scores, indices = index.search(query, K_SEARCH)

            # Collect neighbors excluding self
            neighbors = []
            for idx in indices[0]:
                if idx != i and idx < total:
                    neighbor = corpus[idx]
                    neighbors.append((neighbor["text"], neighbor["label"]))
                if len(neighbors) >= K_SEARCH - 1:
                    break

            # With RAG
            rag_instruction = build_rag_instruction(target_text, neighbors)
            f_rag.write(json.dumps({
                "instruction": rag_instruction,
                "output": target_label,
            }, ensure_ascii=False) + "\n")

            # Without RAG
            plain_instruction = build_plain_instruction(target_text)
            f_plain.write(json.dumps({
                "instruction": plain_instruction,
                "output": target_label,
            }, ensure_ascii=False) + "\n")

            if (progress + 1) % PROGRESS_INTERVAL == 0 or progress == count - 1:
                print(f"    [{progress+1}/{count}] {100*(progress+1)/count:.1f}%")

    rag_size = os.path.getsize(rag_path) / (1024 * 1024)
    plain_size = os.path.getsize(plain_path) / (1024 * 1024)
    print(f"    {rag_path} ({rag_size:.1f} MB, {count} records)")
    print(f"    {plain_path} ({plain_size:.1f} MB, {count} records)")


def main():
    # Load corpus
    print("Loading corpus...")
    corpus = []
    with open(CORPUS_PATH, "r", encoding="utf-8") as f:
        for line in f:
            corpus.append(json.loads(line))
    total = len(corpus)
    print(f"  Corpus size: {total}")

    # Load splits
    print("Loading splits...")
    with open(SPLITS_PATH, "r", encoding="utf-8") as f:
        splits = json.load(f)
    print(f"  Split assignments: {len(splits)}")

    # Group corpus indices by split
    split_indices = {"train": [], "val": [], "test": []}
    for i, record in enumerate(corpus):
        split_name = splits.get(str(record["id"]))
        if split_name in split_indices:
            split_indices[split_name].append(i)
    for name, indices in split_indices.items():
        print(f"  {name}: {len(indices)} records")

    # Load embeddings and index
    print("Loading embeddings and FAISS index...")
    embeddings = np.load(EMBEDDINGS_PATH)
    faiss.normalize_L2(embeddings)
    index = faiss.read_index(INDEX_PATH)
    print(f"  Embeddings shape: {embeddings.shape}")
    print(f"  Index size: {index.ntotal}")

    assert total == embeddings.shape[0] == index.ntotal, (
        f"Size mismatch: corpus={total}, embeddings={embeddings.shape[0]}, index={index.ntotal}"
    )

    # Generate data for each split
    print(f"\nGenerating split data...")
    for split_name in ("train", "val", "test"):
        generate_split_data(
            split_name, split_indices[split_name],
            corpus, embeddings, index, total,
        )

    print(f"\nDone!")


if __name__ == "__main__":
    main()
